---
title: "Disturbance History"
author: "Allie Weill"
date: "June 23, 2016"
output: html_document
---
```{r load-libraries}
library(raster)
library(rgdal)
library(dismo)
library(spatial.tools)
```
## Load files from the AOP external drive
```{r load-from-aop}
setwd("/Volumes/AOP-NEON1-4/D17/SOAP/2013/")
tileDir <- "/Volumes/AOP-NEON1-4/D17/SOAP/2013/SOAP_L2/SOAP_Spectrometer/Veg_Indices"
rasterList <- list.files(tileDir, full.names = TRUE, pattern = "\\NDNI.tif$")
# create a boolean list of rasters in the extent window == 1
# remove NA and get the final list of rasters to mosaic
rasterList <- rasterList[!is.na(rasterList)]
rast.list <- list()
x=1
for(aRaster in rasterList) {
  suppressWarnings(aRaster <- raster(aRaster))
  if(rotated(aRaster)){
    print("raster rotation detected - skipping")
}
else{
    rast.list[x] <- stack(aRaster)
    x <- x + 1
}
}

  
rast.list
rast.list$fun <- max
rast.mosaic <- do.call(mosaic, rast.list)
plot(rast.mosaic)
```


```{r load-fire-file}
# load and combine raster files
setwd("/Users/alweill/Documents/data/NEONDI-2016/")
soap <- rast.mosaic
#load fire data for CA
fires <- raster("/Users/alweill/Documents/data/NEONDI-2016/ExtraData/CAfiresP2.tif")
cellStats(fires,range)
```

```{r crop-fires}

plot(soap)
fires_soap <- crop(fires,soap)
fires_soap <- spatial_sync_raster(fires_soap,soap)
extent(fires_soap)
#plot fires & soap
plot(soap, legend=FALSE)
plot(fires_soap, add=T)
plot(rPlots,add=T)
text(rPlots,labels=rPlots$IDlist)
head(plots)
head(fires_soap)
cellStats(fires,max)
plot(soap, add=T)
rStack <- stack(soap,fires_soap)
```

```{r generate-random-plots}
## generate random plots to sample
rPoints <- randomPoints(soap,30)
rPoints
IDlist <- c(1:30)
rPlots <- data.frame(IDlist,rPoints)
rPlots <- SpatialPointsDataFrame(rPoints,rPlots)
rPlots
```
```{r get-six-plots}
## set plots to be the 6 boundary plots that match up with real field data
allPlots <- readOGR("/Users/alweill/Documents/data/NEONDI-2016/NEONdata/D17-California/SOAP/vector_data/SOAP_centroids_base/SOAP_base_centroids/","SOAP_base_centroids")
rPlots <- allPlots

```

```{r read-veg-data}
setwd("/Volumes/AOP-NEON1-4/D17/SOAP/2013/")
vegdata <- read.csv("/Volumes/AOP-NEON1-4/D17/Field_Data/2013/Sampling_Data/")
SOAPveg <- vegdata[vegdata$siteid=="SOAP",]
str(SOAPveg$easting)
IDlist <- c(1:nrow(SOAPveg))
rPoints <- cbind(SOAPveg$easting,SOAPveg$northing)
rPlots <- data.frame(IDlist,rPoints)
rPlots <- SpatialPointsDataFrame(rPoints,rPlots)

```


```{r extract-data}
eStack <- extract(rStack, 
                   rPlots,
                   buffer = 1,
                   fun = max,#function is mean value
                   sp = TRUE, #give spatial object back
                   stringAsFactors = FALSE)
#w <- rPlots[rPlots$M_Order==255,]

```

```{r add-to-datasets}
# Calculate Time since fire and add as column
eStack@data$TSF <- 2016-eStack@data$CAfiresP2/10000
eStack@data$TSF[eStack@data$TSF==2016] <- NA
# add categorical B vs UB columm
eStack@data$burned <- ifelse(eStack@data$CAfiresP2>0,"B","UB")
eStack$burned
un <- eStack[eStack$M_Order==255,]
head(un)
## create smaller dataframe to plot
temp <- data.frame(eStack@data$burned,eStack@data$layer,eStack@data$TSF,as.character(eStack@data$CAfiresP2/10000))
names(temp) <- c("Burned","Layer","TSF","Year")
par(mfrow=c(1,2))
plot(temp$Year,temp$Layer)
plot(temp$Burned,temp$Layer)
                    
```

```{r add-regression}
library(ggplot2)
p <- ggplot(temp, aes(x=TSF, y = Layer)) +
  geom_point() +
  ylab("Max LiDAR Height") +
  xlab("TSF")+
   xlim(c(50,100)) +
  ylim(c(0,1)) +
  geom_smooth(method=lm)

p + theme(panel.background = element_rect(colour = "grey")) +
  ggtitle("Layer Derived vs TSF") +
  theme(plot.title=element_text(family="sans", face="bold", size=20, vjust=1.9)) +
  theme(axis.title.y = element_text(family="sans", face="bold", size=14, angle=90, hjust=0.54, vjust=1)) +
  theme(axis.title.x = element_text(family="sans", face="bold", size=14, angle=00, hjust=0.54, vjust=-.2))
m <- lm(Layer~Year,temp)
summary(m)
```

## AOP Function
```{r aop-functions}
merge_AOP_tiles <- function(rasterList, outFileName){
  message(paste0("Now running ", basename(rasterList[1])))
  # get list of files from the server
  # 
  
  # create a boolean list of rasters in the extent window == 1
  finalList <- lapply(rasterList, rastInClip, clipShp = clipExtent)
  # remove NA and get the final list of rasters to mosaic
  finalList <- finalList[!sapply(finalList,is.null)]
  
  # # create list of rasters
  # rast.list <- list()
  # for(i in 1:length(finalList)) { rast.list[i] <- stack(finalList[i]) }
  # for(i in 1:length(new)) { rast.list[i] <- stack(new[i]) }
  
  # 
  # crop each raster in list - not sure if it's faster to crop now or after mosaicking
  # rast.list <- lapply(rast.list, crop, clipExtent)
  # mosaic rasters
  # note removed () from the function max call for windows
  finalList$fun <- max
  finalList$tolerance <- .5
  rast.mosaic <- do.call(mosaic, finalList)
  # plot(rast.mosaic)
  
  # write geotiff
  writeRaster(rast.mosaic,
              filename=outFileName,
              format="GTiff",
              options="COMPRESS=LZW",
              overwrite = TRUE,
              NAflag = -9999,
              datatype="FLT4S") # ensure it's writing to 32 bit
  
  # for those who want to plot the final raster to check it out
  # return(rast.mosaic)
}

```

