---
title: "Random Forest Revised"
author: "Kristin Braziunas"
date: "June 24, 2016"
output: html_document
---

## Put LiDAR and HSI data together in a datacube

```{r combine data}

HI.LiDAR.data<-stack(HI.data, LiDAR.data)

# write a function to compare extents and crop layers if they are different
same_extent<-function(raster1, raster2) {
  if (extent(raster1)==extent(raster2)) {
    print("Rasters have same extent")
  } else {
    overlap<-raster::intersect(extent(raster1), extent(raster2))
    # crop both rasters
    # might be good to check which is bigger and compare
    print("Extents are different, Cropping data")
    raster1<-crop(raster1, overlap)
    raster2<-crop(raster2, overlap)
    # create a stack of the new rasters
  }
    raster.stack<-stack(raster1, raster2)
    return(raster.stack)
}

overlap<-raster::intersect(extent(HI.LiDAR.data), extent(all.bands.stack.flight1))
HI.LiDAR.data<-crop(HI.LiDAR.data, overlap)

# test this
same_extent(HI.LiDAR.data, all.bands.stack.flight1)

all.data3<-stack(HI.LiDAR.data, all.bands.stack.flight1)

# check our data

all.data<-all.data3
# no NAs in this dataframe
```

##  Make a df of the indices and examine which are correlated

```{r corr-variables}

# look at correlation bt variables
all.data.df<-as.data.frame(all.data)
cordf<-na.omit(all.data.df)
str(cordf)

# if more than 0.4, correlated, don't use some or put interaction'
coor.cordf<-round(cor(cordf),2)
#export as csv to variables.correlation
# write.csv(coor.cordf,"../Outputs/var_cor_no_reflectance.csv")

```

## Sample HSI and LiDAR data at stem points and get training and validation data

```{r sample_cube_at_stems}

# Get just the stems that are in flight 1
stems_flight1<-raster::intersect(soap_insitu, all.data)
# ?intersect

# Should we sample at 1m pixel or take neighbors? Look at crown diameter stats to decide
summary(stems_flight1$maxcanopyd)
# Mean (2.34) and median (1.6) max canopy diameter is over 1m, so sample larger that 1m cell. Create buffers for maxcanopyd/2 for each stem
#The buffer can be specified as a single value, or as a vector of the length of the number of points

buffers<-(stems_flight1$maxcanopyd)/2

# sample buffer specific to mean crown width. The small argument returns a number even if the buffer doesn't include a cell center. Use the mean function so if the buffer includes multiple cells, it will take mean value of those cells.
# sampled_points<-extract(all.data, soap_insitu, buffer=buffers, small=TRUE, fun=mean, na.rm=TRUE)
# Error: Error in apply(x, 2, fun2) : dim(X) must have a positive length

# work-around for the error that happens above
sampled_points1<-extract(all.data, stems_flight1, buffer=buffers, small=TRUE)

# The below workaround didn't work:
# sampled_points2<-lapply(sampled_points1, function(x) ifelse(is.matrix(x), colMeans(x), x))
# sampled_points<-do.call(rbind, sampled_points2)

# install.packages("plyr")
library("plyr")


results.df <- as.data.frame(t(sampled_points1[[1]]))
for (i in 2:length(sampled_points1)) {
  if (is.matrix(sampled_points1[[i]])) {
    row.result <- as.data.frame(t(colMeans(sampled_points1[[i]])))
  } else {
    row.result <- as.data.frame(t(sampled_points1[[i]]))
  } 
  results.df <- rbind(results.df, row.result)
}

# combine
sampled_points<-cbind(results.df,stems_flight1$taxonid) 

head(sampled_points)

### check this out to see if it makes sense. For example, measured tree height vs. sampled tree height and compare w just using global buffer radius

```


```{r rename-column }

# rename
names(sampled_points)[names(sampled_points)=="stems_flight1$taxonid"]<-"SOAP_ID"

ncol(sampled_points)

```

## Random forest classification

```{r random_forest_classification}
# Machine or ensemble learning method. Can do both regression and classification tasks, and undertakes dimensional reduction methods, treats missing values, outlier values and other essential steps of data exploration. It is a type of ensemble learning method, where multiple CART models are combined

# Set a random seed so that results are reproducible next time we load the code - because this process has two sources of randomness (bagging for bootstrap aggregating takes subset of rows and only running subset of samples each time and subset of predictor variables (sqrt of those available))

set.seed(3693)

fit1 <- randomForest(as.factor(sampled_points$SOAP_ID) ~ .,
                      data=sampled_points, 
                      importance=TRUE, 
                      ntree=5000)
# ntree is number of trees to grow

# What variables were important?
varImpPlot(fit1)

```

## Now try some other packages to visualize trees

Note that other packages process trees differently than randomForest.

```{r visualize-trees}

## try rpart
library(rpart)

soap.rpart <- rpart(as.factor(sampled_points$SOAP_ID) ~ ., 
               data=sampled_points,
               method="class") 
printcp(soap.rpart)

plot(soap.rpart)
text(soap.rpart)

```
